### ISSUE TITLE
Menu not displaying as expected

### ISSUE THREAD

**Issue by lsr1981** [richardblyth/Blank-WordPress-Theme#1]
Hello,

Just installed this theme on a test site to try it out as was wanting a basic starter theme to work with.

Noticed what might be an issue with the menu, I was assuming that the main menu would use the styling from Foundation but it seems to just be a standard list.

I have changed the 'theme name' in functions.php to 'Custom Theme' as well as editing the style.css title to 'Theme Name: Custom Theme' as well as customising the menus in WordPress but the output is as follows.

![screenshot 2015-04-21 15 48 37](https://cloud.githubusercontent.com/assets/4931056/7255062/d5e7972a-e83e-11e4-9c33-fb58a4049b03.png)

Have I missed something?

Thanks,

Lee

**Comment by richardblyth** [comment]
Hi Lee, thanks for trying it out.

I designed the it to be very bare-bones - in my day-to-day projects, menus especially very so much from project to project and rarely do the use Foundation's menu styling. As such, at present there is very minimal CSS/LSS.

That said, if you bob this into your header.less file, it should give you some basic menu styling;

```
  .menu {
    height: 100%;
    list-style: none;
    margin: 0;
    padding: 0;

    li {
      display: inline-block;
      height: 100%;

      a {
        display: block;
        height: 100%;
      }
      a:hover,
      .active-menu-item {
      }
    }

    /* Current Page Indicator */
    .current-menu-item,
    .current-page-parent {
      a {
      }
    }

    /* Drop down */
    .menu-item-has-children {

      .sub-menu {
        display: none; /*js*/
        left: 0;
        margin: 0;
        padding: 0.625em 0;
        position: absolute;
        top: 4.750em; /*76px*/
        width: 100%;

        li {
          float: left;
          display: inline-block;

          a {
          }
          a:hover {
          }
        }
      }
    }
  }
```

And the following into your main.js:

//Main Menu
  $('li.menu-item-has-children').mouseover(function () {  
    $('ul:first', this).stop(true, true).show();
    $('a:first', this).addClass('active-menu-item');
  });  
  $('li.menu-item-has-children').mouseleave(function () {  
    $('ul:first', this).stop(true, true).hide();
    $('a:first', this).removeClass('active-menu-item');
  });

You will need to tweak these to suit your design and you will likely find you will need tweak header.php accordingly, e.g. the menu may be better on it's own .row for your site.

**Comment by lsr1981** [comment]
Thank you for the prompt reply. That makes sense I will take a look at adding those and editing the menu layout accordingly, just thought I would check that I had not missed something first.

I do love how it is very bare-bones as some of the other themes I have had a look at for developing using frameworks tend to be overly complex which defeats the object of using them as a starting point to begin with.

**Comment by richardblyth** [comment]
Thank you Lee, I'm glad you're finding it useful and that was exactly what I'd hoped to achieve :) 

I had been toying with the idea of adding an optional stylesheet which would allow people to make better use of Foundation's built in CSS/functions if they wished. I'll also add to the Readme for future versions
